config/routes.rb
Rails.application.routes.draw do

# //////////ROOT ROUTE///////////////////////
  root 'home#index'

# //////////SESSIONS ROUTES/////////////////
  get    '/login/:title', to: 'sessions#new',     as: :new_login
  post   '/login/:title', to: 'sessions#create',  as: :login
  delete '/logout',       to: 'sessions#destroy', as: :logout

# /////////RESOURCE/CRUD ROUTES/////////////
  resources :instructors
  resources :students
  resources :students_quizzes
  resources :instructors_quizzes
  resources :cohorts

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question


end

app/models/cohort.rb
class Cohort < ActiveRecord::Base

  has_many :students
  has_many :quizzes
  belongs_to :instructor
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_secure_password

  has_many :cohorts
  has_many :students, through: :cohorts

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :quiz
  has_many :answers

accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base

  belongs_to :cohort
  belongs_to :student
  has_many :questions

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_secure_password

  belongs_to :cohort
  has_many :quizzes


  before_create do
    self.cohort = Cohort.all.first if cohort.blank?
  end

  # def self.save_data_from_api
  #   response = HTTParty.get('http://104.131.73.180/api/v1/students')
  #   students = response['students'].map do |student|
  #     s = Student.new
  #     s.name = "#{student['data']['first']} #{student['data']['last']}"
  #     s.email = student['contact']['email']
  #     s.save
  #     s
  #   end
  #   students.select(&:persisted?)

  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # @student = Student.find(session[:student_id])

  def current_instructor
    @current_instructor ||= Instructor.find_by_id(session[:instructor_id]) if session[:instructor_id]
    if @current_instructor
      true
    else
      logout
    end
  end

  def current_student
    @current_student ||= Student.find_by_id(session[:student_id]) if session[:student_id]
    if @current_student
      true
    else
      logout
    end
  end

  # makes current_instructor available in our views
  helper_method(:current_instructor)
  helper_method(:current_student)

  def authorize_instructor
    redirect_to '/login/instructor' unless current_instructor
  end

  def authorize_student
    redirect_to '/login/student' unless current_student
  end

  def logout
    session[:student_id], session[:instructor_id] = nil
  end

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  def show
    @cohort = Cohort.find_by(instructor_id: params[:id])
  end

  def new
    @cohort = Cohort.new
    @instructor_id = session[:instructor_id]
  end

  def create
    @cohort = Cohort.create(cohort_params)
    redirect_to cohort_path(@cohort)
  end

  def cohort_params
    params.require(:cohort).permit(:name, :instructor_id, :room, :producer)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
before_action(:authorize_instructor, :except => [:new, :create])

  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def create
    instructor = Instructor.create(instructor_params)
    redirect_to instructor_path(instructor)
  end

  def instructor_params
    params.require(:instructor).permit(
        :name,
        :email,
        :password,
        :authenticity_token
      )
  end

end

app/controllers/instructors_quizzes_controller.rb
class InstructorsQuizzesController < ApplicationController

  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def create
    # binding.pry
    @quiz = Quiz.create(quiz_params)
    @question = Question.new
    grab_questions
    grab_answers
    redirect_to instructors_quiz_path(@quiz)
  end

  def new
    @instructors_quiz = Quiz.new
    # 3.times do
      question= @instructors_quiz.questions.build
      4.times { question.answers.build }
    # end
  end

  def quiz_params
    params.require(:quiz).permit(:name,:cohort_id,:questions_attributes)
  end

  def grab_questions
    question = params["quiz"]["questions_attributes"]["0"]["content"]
    @question.content = question
    @question.quiz_id = @quiz.id
    @question.save
  end

  def grab_answers
    answers = params["quiz"]["questions_attributes"]["0"]["answers_attributes"]
    answers.each do |a|
      b = Answer.new
      b.content = a[1]["content"]
      b.question_id = @question.id
      b.save
    end
  end

end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController

  def index
    @student = Student.find(session[:student_id])
    # binding.pry
    # @student.cohort.quizzes
    quiz_array = Quiz.where(been_taken: false && cohort_id == @student.cohort_id)

    if(quiz_array == [])
      @response = "No quizzes, come back later"
    else
      @quizs = quiz_array
      @response = "You have to do these quizzes!"
    end
  end

    # quiz_array.each do |q|
    #   q.students.each do |s|
    #     s.id == @student.id
    #   end
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # handle the lookup and auth
    if(params[:title] == 'instructor')
      instructor = Instructor.find_by({email: params[:email]})

      if instructor && instructor.authenticate(params[:password])
        session[:instructor_id] = instructor.id
        redirect_to instructor_path(instructor)
      else
        render :new
      end
    elsif(params[:title] == 'student')
      student = Student.find_by({email: params[:email]})

      if student && student.authenticate(params[:password])
        session[:student_id] = student.id
        redirect_to student_path(student)
      else
        render :new
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action(:authorize_student, :except => [:new, :create])

  def show
    # Student.save_data_from_api
    @students = Student.all
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    redirect_to student_path(student)
  end

  def student_params
    params.require(:student).permit(
        :name,
        :email,
        :password,
        :authenticity_token
      )
  end


end

app/controllers/students_quizzes_controller.rb
class StudentsQuizzesController < ApplicationController

  def index
    quiz_array = Quiz.where('been_taken = ? AND student_id = ?', false, session[:student_id])
    # quiz_array = Quiz.where(been_taken: false && :student_id == session[:student_id])
    @student = Student.find(session[:student_id])
    # binding.pry
    # @student.cohort.quizzes
    quiz_array = Quiz.where(been_taken: false && cohort_id == @student.cohort_id)

    if(quiz_array == [])
      @response = "No quizzes, come back later"
    else
      @quizs = quiz_array
      @response = "You have to do these quizzes!"
    end
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :instructor_id, value: @instructor_id %>
  <%= f.label :room %>
  <%= f.text_field :room %>
  <%= f.label :producer %>
  <%= f.text_field :producer %>
  <%= f.submit "Create Cohort" %>
<% end %>

app/views/cohorts/new.html.erb
<h2> Create a new Cohort </h2>

 <%= render "form" %>

app/views/cohorts/show.html.erb
<h1>Welcome to <%=@cohort.name.capitalize%></h1>

      <%= button_to 'Create New Quiz', new_instructors_quiz_path, method: :get, :class => :button %>
      <%= button_to 'View all Quizzes ' , instructors_quizzes_path, method: :get, :class => :button %>

app/views/home/index.html.erb
<center>
<h1>Welcome to Quiz Creator</h1>

<TABLE BORDER="0">
<TR>

<TD><%= button_to "Instructor Login", '/login/instructor', method: "get", :class => :to_login_button, :id => :instructor_login %></TD>

<TD><%= button_to "Student Login", '/login/student', method: "get", :class => :to_login_button, :id => :student_login%></TD>

</TR>

</TABLE>
</center>

app/views/instructors/new.html.erb
<center> <h1>Create a new instructor</h1>

<%= form_for(@instructor) do |i|%>
<table>
  <tr>
  <td><%= i.label :name%></td>
  <td><%= i.text_field :name%></td>
</tr>
<tr>
  <td><%= i.label :email%></td>
  <td><%= i.text_field :email%></td>
  </tr>
  <tr>
    <td><%= i.label :password%></td>
    <td><%= i.password_field :password%></td>
  </tr>
  <tr>
    <td><%= i.label :password_confirmation%></td>
    <td><%= i.password_field :password_confirmation%></td>
  </tr>
    <td><%= i.submit%></td>
  </tr>
</table>
<% end %>
</center>

app/views/instructors/show.html.erb
<h1> Welcome <%=@instructor.name%></h1>

<% if @instructor.cohorts == [] %>
  <%= button_to 'Create a new cohort', new_cohort_path, method: :get, :class => :button %>
<% else %>
  <ul>
   <% @instructor.cohorts.each do |c|  %>
    <li>
      <%= button_to c.name.capitalize, cohort_path, method: :get, :class => :button %>
    </li>
   <%end%>
  </ul>
<% end %>

 </ul>

 <%= button_to 'Logout', logout_path, method: :delete %>

app/views/instructors_quizzes/_answer_fields.html.erb
<p>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</p>

app/views/instructors_quizzes/_form.html.erb
<%= form_for @instructors_quiz, :url => instructors_quizzes_path do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
    <%= f.label :cohort_id %><br />
    <%= f.text_field :cohort_id %><br />
  </p>
  <%= f.fields_for :questions do |builder| %>
    <%= render "question_fields", :f => builder %>
  <% end %>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/instructors_quizzes/_question_fields.html.erb
<p>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content, :rows => 3 %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
</p>
<%= f.fields_for :answers do |builder| %>
  <%= render 'answer_fields', :f => builder %>
<% end %>

app/views/instructors_quizzes/index.html.erb
<h1>These are the Quizzes!</h1>

<ul>
  <% @quizzes.each do |q| %>
    <li><%= q.name %></li>
  <% end %>
</ul>

<INPUT TYPE="button" VALUE="Back" onClick="history.go(-1);">
<%= button_to 'Create a New Quiz', new_instructors_quiz_path, method: :get %>
<%= button_to 'Logout', logout_path, method: :delete %>

app/views/instructors_quizzes/new.html.erb
<h2>Create a new Quiz </h2>

 <%= render "form" %>

app/views/instructors_quizzes/show.html.erb
<h1> <%=@quiz.name%> </h1>

<% @quiz.questions.each do |q|%>
  <%= q[:content] %>
  <ul>
  <% q.answers.each do |a| %>
    <li><%= a.content %></li>
  <% end %>
  </ul>
<% end %>

<%= button_to 'Back to all quizzes ' , instructors_quizzes_path, method: :get, :class => :button %>
<%= button_to 'Logout', logout_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizCreator</title>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= link_to image_tag("ga_logo.jpg", :height => 125, :width => 125, :class => :header_logo), "https://generalassemb.ly/"%>
  <h1 class="app_name">GA Quiz Creator</h1>
</header>


<%= yield %>


</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for @quiz do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <%= f.label :cohort_id %>
    <%= f.text_field :cohort_id %>
  </p>
  <%= f.fields_for :questions do |builder| %>
    <%= render "question_fields", :f => builder %>
  <% end %>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/students/new.html.erb
<h1>Create a new Student</h1>

<%= form_for(@student) do |s|%>

  <%= s.label :name%>
  <%= s.text_field :name%><br>
  <%= s.label :email%>
  <%= s.text_field :email%><br>
  <%= s.label :password%>
  <%= s.password_field :password%><br>
  <%= s.label :password_confirmation%>
  <%= s.password_field :password_confirmation%><br>
  <%= s.submit%>
<% end %>

app/views/students/show.html.erb
<h1>Welcome <%= @student.name.capitalize %></h1>

<div class='taken'>
  <ol>
    <% @student.quizzes.each do |q| %>
    <li><a href="/students_quizzes/<%= q.id %>"><%= q.name %></a></li>
    <% end %>
  </ol>
</div>


<%= button_to 'Check for New Quiz', students_quizzes_path, method: :get %>
<%= button_to 'Logout', logout_path, method: :delete %>

app/views/students_quizzes/index.html.erb
<h1>Hola <%= @student.name.capitalize %></h1>
<h1>Looking for new quizzes?</h1>

<% if @quizs == nil %>
  <h2><%= @response %></h2>
<% else %>
  <h2><%= @response %></h2>
  <ul>
    <% @quizs.each do |q| %>
    <li><a href="/students_quizzes/<%=q.id%>"><%= q.name %></a></li>
    <% end %>
  </ul>
<% end %>

<%= button_to 'Logout', logout_path, method: :delete %>

app/views/students_quizzes/show.html.erb
<h1> <%=@quiz.name%> </h1>

<% @quiz.questions.each do |q|%>
  <%= q[:content] %>
  <ul>
  <% q.answers.each do |a| %>
    <li><%= a.content %></li>
  <% end %>
  </ul>
<% end %>

<INPUT TYPE="button" VALUE="Back" onClick="history.go(-1);">